# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2020 Microsoft Corporation
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#

obj-$(CONFIG_FACTORY_UTIL) += fuse_check.o
obj-$(CONFIG_FACTORY_UTIL) += mcfg_check.o
obj-$(CONFIG_FACTORY_UTIL) += surface_util.o
obj-$(CONFIG_SURFACE_LIBRARY) += xbl_hlos_hob.o
obj-$(CONFIG_SURFACE_LIBRARY) += telemetry.o
obj-$(CONFIG_SURFACE_LIBRARY) += display_state.o
obj-$(CONFIG_SURFACE_LIBRARY) += pen_charger.o
obj-$(CONFIG_SURFACE_LIBRARY) += surface_product_id.o
obj-$(CONFIG_SURFACE_LIBRARY) += hob_mem.o
